libname fs "D:\bigedu";

/*전체 입원환자의 약품 정보*/
PROC SQL;
	CREATE TABLE NOT_COM_SICK_1 AS
	SELECT B.JID AS JID, B.MAIN_SICK AS SICK, A.GNL_CD AS MED_INFO, B.MID AS MID
	FROM FS.T300 AS A
	LEFT JOIN FS.T200 AS B
	ON A.MID = B.MID
	WHERE B.FOM_TP_CD IN ('021','121') AND SUBSTR(B.MAIN_SICK, 1,3) IN ('I63','I67','O22','O87');
QUIT;

/* 주상병 4개로 입원한 사람의 입원날짜 추출 */
PROC SQL;
	CREATE TABLE OUT_HOS AS
	SELECT JID AS JID, MID AS MID, RECU_FR_DD AS START, RECU_TO_DD AS END
	FROM FS.T200
	WHERE FOM_TP_CD IN ('021','121') AND SUBSTR(MAIN_SICK,1,3) IN ('I63','I67','O22','087');
QUIT;


/* 주상병 4개의 병을 가진 사람의 약품 사용량(1-1~1-2합쳐야함) */
PROC SQL;
	CREATE TABLE NOT_COM_SICK_1_1 AS
	SELECT B.JID AS JID, A.MID AS MID, A.TOT_USE_QTY_OR_EXEC_FQ AS TOT_USE , A.TOT_INJC_DDCNT_EXEC_FQ AS DUE
	FROM FS.T300 AS A
	LEFT JOIN WORK.NOT_COM_SICK_1 AS B
	ON A.MID = B.MID;
QUIT;


/* MEDICINE TABLE T530 이랑 한 것 */
PROC SQL;
	CREATE TABLE MEDICINE2 AS
	SELECT B.GNL_CD
		, AVG(B.TOT_USE_QTY_OR_EXEC_FQ) AS AVG_TOTAL_USE
		, AVG(B.DY1_MDCT_QTY) AS AVG_1DAY_DOS
		, AVG(B.TOT_INJC_DDCNT_EXEC_FQ) AS AVG_DUE
		, SUM(B.TOT_INJC_DDCNT_EXEC_FQ) AS SUM_DUE
	FROM FS.T200 AS A
	LEFT JOIN FS.T530 AS B
	ON A.MID = B.MID
	WHERE SUBSTR(A.MAIN_SICK,1,3) IN('I63','I67','O22','O87') AND A.FOM_TP_CD IN('021','061')
	GROUP BY B.GNL_CD;
QUIT;

/* agg 만들기 */
DATA AGG_AG;
	SET FS.T200;
	IF 0<=PAT_AGE<=5 THEN AGG = 1;
	ELSE IF 6<=PAT_AGE<=10 THEN AGG = 2;
	ELSE IF 11<=PAT_AGE<=15 THEN AGG = 3;
	ELSE IF 16<=PAT_AGE<=20 THEN AGG = 4;
	ELSE IF 21<=PAT_AGE<=25THEN AGG = 5;
	ELSE IF 26<=PAT_AGE<=30THEN AGG = 6;
	ELSE IF 31<=PAT_AGE<=35 THEN AGG = 7;
	ELSE IF 36<=PAT_AGE<=40THEN AGG = 8;
	ELSE IF 41<=PAT_AGE<=45 THEN AGG = 9;
	ELSE IF 46<=PAT_AGE<=50 THEN AGG = 10;
	ELSE IF 51<=PAT_AGE<=55 THEN AGG = 11;
	ELSE IF 56<=PAT_AGE<=60 THEN AGG = 12;
	ELSE IF 61<=PAT_AGE<=65 THEN AGG = 13;
	ELSE IF 66<=PAT_AGE<=70 THEN AGG = 14;
	ELSE IF 71<=PAT_AGE<=75 THEN AGG = 15;
	ELSE IF 76<=PAT_AGE<=80 THEN AGG = 16;
	ELSE IF 81<=PAT_AGE THEN AGG=17;
RUN;

/* 연도별 뇌경색증 연령대에 따른 환자 추세 파악 */ 
PROC SQL;
	CREATE TABLE CVT_AGG AS
	SELECT COUNT(JID) AS JID_CNT, AGG AS AG
	FROM AGG_AG
	WHERE SUBSTR(MAIN_SICK, 1,3) IN ('I63','I67','O22','087') AND FOM_TP_CD IN ('031')
	GROUP BY AGG;
QUIT;

